
[project]
name = "a2a"
version = "0.1.0"
description = "Minimal working A2A protocol package for local testing"
authors = [{name = "Local Dev"}]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
